Add SoH Elastic server to main experiment

diff --git a/phenix/src/go/api/config/default/elasticsearch.yml b/phenix/src/go/api/config/default/elasticsearch.yml
--- a/phenix/src/go/api/config/default/elasticsearch.yml
+++ b/phenix/src/go/api/config/default/elasticsearch.yml
@@ -6,6 +6,7 @@ spec:
   compress: false
   deb_append: ' --components=main,restricted,universe,multiverse'
   format: qcow2
+  include_miniccc: /usr/local/bin/miniccc
   mirror: http://us.archive.ubuntu.com/ubuntu/
   overlays: null
   packages:
@@ -23,19 +24,79 @@ spec:
   - dbus
   - linux-image-generic
   - linux-headers-generic
+  - python3-cffi-backend # fixes python3-cryptography install issue on focal
   - xserver-xorg-video-qxl
   - xserver-xorg-video-vesa
   - xubuntu-desktop
   - firefox
   - tcpdump
   ramdisk: false
-  release: bionic
+  release: focal
   script_order:
   - POSTBUILD_APT_CLEANUP
   - POSTBUILD_NO_ROOT_PASSWD
   - POSTBUILD_PHENIX_HOSTNAME
+  - POSTBUILD_PHENIX_BASE
   - /phenix/vmdb/scripts/elasticsearch.sh
   scripts:
+    POSTBUILD_APT_CLEANUP: |
+      apt clean || apt-get clean || echo "unable to clean apt cache"
+    POSTBUILD_NO_ROOT_PASSWD: |
+      sed -i 's/nullok_secure/nullok/' /etc/pam.d/common-auth
+      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
+      sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
+      sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
+      sed -i 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
+      passwd -d root
+    POSTBUILD_PHENIX_HOSTNAME: |
+      echo "phenix" > /etc/hostname
+      sed -i 's/127.0.1.1 .*/127.0.1.1 phenix/' /etc/hosts
+      cat > /etc/motd <<EOF
+
+      ██████╗ ██╗  ██╗███████╗███╗  ██╗██╗██╗  ██╗
+      ██╔══██╗██║  ██║██╔════╝████╗ ██║██║╚██╗██╔╝
+      ██████╔╝███████║█████╗  ██╔██╗██║██║ ╚███╔╝
+      ██╔═══╝ ██╔══██║██╔══╝  ██║╚████║██║ ██╔██╗
+      ██║     ██║  ██║███████╗██║ ╚███║██║██╔╝╚██╗
+      ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚══╝╚═╝╚═╝  ╚═╝
+
+      EOF
+      echo "\nBuilt with phenix image on $(date)\n\n" >> /etc/motd
+    POSTBUILD_PHENIX_BASE: |
+      mkdir -p /etc/phenix/startup
+      mkdir -p /etc/systemd/system/multi-user.target.wants
+      mkdir -p /usr/local/bin
+      cat > /etc/systemd/system/miniccc.service <<EOF
+      [Unit]
+      Description=miniccc
+      [Service]
+      ExecStart=/usr/local/bin/miniccc -v=false -serial /dev/virtio-ports/cc -logfile /var/log/miniccc.log
+      [Install]
+      WantedBy=multi-user.target
+      EOF
+      cat > /etc/systemd/system/phenix.service <<EOF
+      [Unit]
+      Description=phenix startup service
+      After=network.target systemd-hostnamed.service
+      [Service]
+      Environment=LD_LIBRARY_PATH=/usr/local/lib
+      ExecStart=/usr/local/bin/phenix-start.sh
+      RemainAfterExit=true
+      StandardOutput=journal
+      Type=oneshot
+      [Install]
+      WantedBy=multi-user.target
+      EOF
+      ln -s /etc/systemd/system/miniccc.service /etc/systemd/system/multi-user.target.wants/miniccc.service
+      ln -s /etc/systemd/system/phenix.service /etc/systemd/system/multi-user.target.wants/phenix.service
+      cat > /usr/local/bin/phenix-start.sh <<EOF
+      #!/bin/bash
+      for file in /etc/phenix/startup/*; do
+        echo \$file
+        bash \$file
+      done
+      EOF
+      chmod +x /usr/local/bin/phenix-start.sh
     /phenix/vmdb/scripts/elasticsearch.sh: |
       curl -k -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.9.3-amd64.deb
       curl -k -L -O https://artifacts.elastic.co/downloads/kibana/kibana-oss-7.9.3-amd64.deb
@@ -48,7 +109,7 @@ spec:
       ln -s /etc/systemd/system/kibana.service /etc/systemd/system/multi-user.target.wants/kibana.service
       cat > /root/.profile <<EOF
       # ~/.profile: executed by Bourne-compatible login shells.
-      if [ "$BASH" ]; then
+      if [ "\$BASH" ]; then
         if [ -f ~/.bashrc ]; then
           . ~/.bashrc
         fi
@@ -77,28 +138,5 @@ spec:
       Terminal=false
       Hidden=false
       EOF
-    POSTBUILD_APT_CLEANUP: |
-      apt clean || apt-get clean || echo "unable to clean apt cache"
-    POSTBUILD_NO_ROOT_PASSWD: |
-      sed -i 's/nullok_secure/nullok/' /etc/pam.d/common-auth
-      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
-      sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
-      sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
-      sed -i 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
-      passwd -d root
-    POSTBUILD_PHENIX_HOSTNAME: |
-      echo "phenix" > /etc/hostname
-      sed -i 's/127.0.1.1 .*/127.0.1.1 phenix/' /etc/hosts
-      cat > /etc/motd <<EOF
-
-      ██████╗ ██╗  ██╗███████╗███╗  ██╗██╗██╗  ██╗
-      ██╔══██╗██║  ██║██╔════╝████╗ ██║██║╚██╗██╔╝
-      ██████╔╝███████║█████╗  ██╔██╗██║██║ ╚███╔╝
-      ██╔═══╝ ██╔══██║██╔══╝  ██║╚████║██║ ██╔██╗
-      ██║     ██║  ██║███████╗██║ ╚███║██║██╔╝╚██╗
-      ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚══╝╚═╝╚═╝  ╚═╝
-
-      EOF
-      echo "\nBuilt with phenix image on $(date)\n\n" >> /etc/motd
-  size: 10G
+  size: 25G
   variant: minbase
